# Generated by Django 2.2.14 on 2020-12-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_auto_20201220_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
