# Generated by Django 2.2.14 on 2020-12-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_auto_20201220_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
