# Generated by Django 2.2.14 on 2020-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.TextField(default='this is a test '),
            preserve_default=False,
        ),
    ]
