# Generated by Django 2.2.14 on 2020-12-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_item_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
    ]
